# Generated by Django 5.1.5 on 2025-02-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_customuser_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_manager",
            field=models.BooleanField(default=False, verbose_name="Менеджер"),
        ),
    ]
