# Generated by Django 5.1.5 on 2025-01-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "email",
                    models.EmailField(help_text="Укажите email", max_length=254, unique=True, verbose_name="Email"),
                ),
                (
                    "fio",
                    models.CharField(
                        help_text="Укажите свои фамилию, имя и отчество", max_length=150, verbose_name="ФИО"
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True, verbose_name="Комментарий")),
            ],
            options={
                "verbose_name": "Получатель рассылки",
                "verbose_name_plural": "Получатели рассылки",
            },
        ),
    ]
