# Generated by Django 5.1.5 on 2025-01-25 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_sent_at", models.DateTimeField(auto_now_add=True)),
                ("finish_sent_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("created", "Создана"), ("launched", "Запущена"), ("Completed", "Завершена")],
                        default="created",
                        max_length=10,
                        verbose_name="Статус рассылки",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="mailing.message"
                    ),
                ),
                (
                    "subscribers",
                    models.ManyToManyField(related_name="newsletter_subscribers", to="mailing.subscriber"),
                ),
            ],
        ),
    ]
