# Generated by Django 5.1.5 on 2025-01-25 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0003_newsletter"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newsletter",
            options={"verbose_name": "Рассылка", "verbose_name_plural": "Рассылки"},
        ),
    ]
