# Generated by Django 5.1.5 on 2025-01-25 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0004_alter_newsletter_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscriber",
            options={
                "ordering": ["fio"],
                "verbose_name": "Получатель рассылки",
                "verbose_name_plural": "Получатели рассылки",
            },
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="finish_sent_at",
            field=models.DateTimeField(verbose_name="Дата и время окончания отправки"),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="message",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="mailing.message"),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="start_sent_at",
            field=models.DateTimeField(verbose_name="Дата и время первой отправки"),
        ),
        migrations.CreateModel(
            name="AttemptSent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(choices=[("Успешно", "Успешно"), ("Не успешно", "Не успешно")], max_length=10),
                ),
                ("server_response", models.TextField(verbose_name="Ответ почтового сервера")),
                (
                    "newsletter",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="mailing.newsletter"),
                ),
            ],
        ),
    ]
