# Generated by Django 5.1.5 on 2025-01-25 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0005_alter_subscriber_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="message",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="mailing.message"
            ),
        ),
    ]
