# Generated by Django 5.1.5 on 2025-01-26 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0007_attemptsent_owner_message_owner_newsletter_owner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attemptsent",
            name="newsletter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="newsletters", to="mailing.newsletter"
            ),
        ),
        migrations.AlterField(
            model_name="attemptsent",
            name="server_response",
            field=models.TextField(blank=True, null=True, verbose_name="Ответ почтового сервера"),
        ),
    ]
