# Generated by Django 5.1.5 on 2025-01-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0008_alter_attemptsent_newsletter_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="finish_sent_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Дата и время окончания отправки"),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="start_sent_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Дата и время первой отправки"),
        ),
    ]
