# Generated by Django 5.1.5 on 2025-01-26 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0009_alter_newsletter_finish_sent_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newsletter",
            options={
                "permissions": [
                    ("blocking_service_users", "Can blocking service users"),
                    ("disabling_newsletter", "Can disabling Newsletter"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
