# Generated by Django 5.1.5 on 2025-01-26 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0010_alter_newsletter_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newsletter",
            options={
                "permissions": [("disabling_newsletter", "Can disabling Newsletter")],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
