# Generated by Django 5.1.5 on 2025-02-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0011_alter_newsletter_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Создана"),
                    ("launched", "Запущена"),
                    ("completed", "Завершена"),
                    ("disabled", "Отключена"),
                ],
                default="created",
                max_length=10,
                verbose_name="Статус рассылки",
            ),
        ),
    ]
